openapi: 3.1.0
info:
    title: 'Memestash Laravel Back-End'
    version: 0.1.0
    description: 'Back-end application based on the Laravel Framework, to be used with Memestash web and/or native app'
    contact: { name: 'Bo Robbrecht', email: bo.robbrecht@student.howest.be, url: 'https://git.ti.howest.be/TI/2020-2021/s4/web-and-mobile-technology/students/bo-robbrecht/memestash/laravel' }
servers:
    - { url: 'http://localhost', description: 'Local url for testing' }
tags: null
paths: null
components:
    schemas: null
    responses: null
    headers: null
    parameters: null
    links: null
    examples: null
