openapi: 3.0.0
info:
  title: 'Memestash Laravel Back-End'
  version: 0.1.0
  description: 'Back-end application based on the Laravel Framework, to be used with Memestash web and/or native app'
  contact: { name: 'Bo Robbrecht', email: bo.robbrecht@student.howest.be, url: 'https://git.ti.howest.be/TI/2020-2021/s4/web-and-mobile-technology/students/bo-robbrecht/memestash/laravel' }
servers:
  - { url: 'http://localhost', description: 'Local url for testing' }
tags:
  - name: Users
    description: All endpoints interacting mainly with users
paths:
  /users:
    get:
      summary: Get all users.
      description: Get all users and basic, non-sensitive information.
      tags:
        - Users
      parameters:
        - $ref: "#/components/parameters/namequery"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
components:
  parameters:
    namequery:
      name: name
      in: query
      schema:
        type: string
      description: Filters the user by name
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Ruiner
